### ISSUE TITLE
No puedo instalar el nuget, me dice que no es compatible con netstandard2.0

### ISSUE THREAD

**Issue by justwooper** [JosueDM94/Xamarin.Google.Maps.Utils#1]
Hola, no me permite instalar el paquete nuget, me dice el siguiente error:

El paquete Xamarin.Google.Maps.Utils 1.0.0 no es compatible con netstandard2.0 (.NETStandard,Version=v2.0). El paquete Xamarin.Google.Maps.Utils 1.0.0 admite:
  - monoandroid81 (MonoAndroid,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

que se puede hacer? gracias

**Comment by JosueDM94** [comment]
Este paquete es un binding de las librerias nativas y solo funciona en Xamarin.Android y Xamarin.iOS, si quieres usarla en Xamarin.Forms debes crear tu Renderer donde implementes la logica nativa de esta libreria.

**Comment by justwooper** [comment]
Ya veo, pero si se puede correr en xamarin.forms si se hacen esos ajustes que mencionas? tienes un ejemplo de como poder hacerlo? gracias

**Comment by JosueDM94** [comment]
Si es posible usarlo en Xamarin.Forms, no tengo un ejemplo publico, puedes checar la documentacion de Xamarin para hacer el custom renderer-> https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/
