### ISSUE TITLE
Xamarin forms

### ISSUE THREAD

**Issue by BurakOgutken** [JosueDM94/Xamarin.Google.Maps.Utils#2]
Can we use this on xamarin forms ?

**Comment by prajaktashindeSilicus** [comment]
Any updates for Xamarin.Forms?

**Comment by JosueDM94** [comment]
You can create your own renderer of GoogleMap and use this binding library on each platform or use the Nuget of this repository https://github.com/amay077/Xamarin.Forms.GoogleMaps.
