### ISSUE TITLE
Update bindings to v0.6.2 (with AndroidX dependencies)

### ISSUE THREAD

**Issue by tipa** [JosueDM94/Xamarin.Google.Maps.Utils#4]
Thanks a lot for these bindings, have been using them since 2 years now!
Any plans to update to the latest version 0.6.2? As Xamarin.Android [slowly migrates over to AndroidX](https://devblogs.microsoft.com/xamarin/androidx-nuget-packages-are-stable/), this could be a good time to also upgrade these bindings.

**Comment by LJungmann** [comment]
As we have more pressure onto upgrading to androidx and we also want to, we would really appreciate an upgrade for the androidx dependencies.

**Comment by JosueDM94** [comment]
The AndroidX Support is fully supported starting in the 1.0.1 Version.

The previous package with the AndroidX Support is now unlistened due to ownership recovery (https://www.nuget.org/packages/Xamarin.GoogleMapsUtils)
