### ISSUE TITLE
.Net Maui Support

### ISSUE THREAD

**Issue by tranhoangnam16705** [JosueDM94/Xamarin.Google.Maps.Utils#8]
Does .NET Maui support is on the roadmap. When the package is expected to be ready for .NET Maui

**Comment by FreakyAli** [comment]
@JosueDM94 Do you see this happening soon?

**Comment by JosueDM94** [comment]
I'll start the support for .Net Maui soon

**Comment by FreakyAli** [comment]
Awesome, make sure you target .Net8 ✌️

**Comment by JosueDM94** [comment]
.Net 8 Support is ready
