### ISSUE TITLE
Version 1.3.5 seems broken

### ISSUE THREAD

**Issue by lufo88ita** [JosueDM94/Xamarin.Google.Maps.Utils#9]
Hi.
First of all: thank you for your work 👍 

I update your library from 1.3.4 to 1.3.5 in my MAUI project that use NET 8.
However when I compile my app (doesn't matter if the target is a real device or the emulator) various error appear:

```
error: package com.google.maps.android.clustering.ClusterManager does not exist
error: package com.google.maps.android.clustering does not exist
error: package com.google.maps.android.clustering.view does not exist
```

And so on. I clean the solution, remove the content of the folder obj/bin. Nothing change.
Also the Resource id "amu_text" seems not available (it's used to customize label appereance in a cluster).

 Can you check this?

**Comment by JosueDM94** [comment]
Hello @lufo88ita, could you help me to test the new version?

I know there is an open discussion/ issue about the Android Resources access in Maui using the Resource class/namespace.
if you are using .Net Android everything should be fine, but if you are using .Net Maui you could use this helper method.

```
public static int GetResourceId(string fileName, string resourceType) =>
        Platform.AppContext.Resources.GetIdentifier(fileName, resourceType, Platform.AppContext.PackageName);
```

**Comment by lufo88ita** [comment]
Sure, I can help you testing. What do you need?

> if you are using .Net Android everything should be fine, but if you are using .Net Maui you could use this helper method.

I will try, but the other error block any test.

**Comment by JosueDM94** [comment]
I tested with the Sample/Demo apps and works on my end. Just need to someone else validate that all the resources and references are available in the new version.

**Comment by JosueDM94** [comment]
I Tested with the Sample/Demo apps and works on my end. Just need to someone else validate that all the resources and references are available in the new version.

**Comment by lufo88ita** [comment]
Hi,
After a month I return on my project whom need your binding library.

I tried to run your sample, but it give me three errors
```
APT2061	failed linking file resources.
	Sample.Android	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\Xamarin.Android.Aapt2.targets	156	
APT2260	resource style/amu_Bubble.TextAppearance.Light (aka com.jdiaz.gmapsutils:style/amu_Bubble.TextAppearance.Light) not found.

APT2260	resource id/amu_text (aka com.jdiaz.gmapsutils:id/amu_text) not found.
	Sample.Android	C:\Progetti\Xamarin.Google.Maps.Utils\Samples\Sample.Android\Resources\layout\multi_profile.xml
```

Maybe I do something wrong?
